### ISSUE TITLE
Failure on the outdoor datatset

### ISSUE THREAD

**Issue by cjxie** [flysoaryun/LF-VIO#10]
Thank you for sharing your guys great works!

The whole thing works great on the indoor datasets but it got worse while I was testing on your outdoor ones. A huge drift was shown during the initialization which is also a problem in vins-mono. It seems to be hard to get a converged result from initialization and keep reinitialization again and again. Is there any suggestion on that?

![image](https://github.com/flysoaryun/LF-VIO/assets/89928234/6e6a994f-214d-406e-bb43-326097db8ac1)

**Comment by flysoaryun** [comment]
Since the outdoor experiment is a supplementary experiment, its hardware including cameras and IMU are completely different from the indoor experiment. We re-tuned all parameters and conducted experiments. The following are our experimental parameters:
```
%YAML:1.0

#common parameters
imu_topic: "/mavros/imu/data_raw"
image_topic: "/mindvision/mindvision/left/image_mono"
output_path: "/media/wt/wt_disk/grass/grass_LF-VIO/output/"

#camera calibration 
model_type: scaramuzza
camera_name: pal
image_width: 1280
image_height: 960
poly_parameters:
   p0: -2.859221e+02 
   p1: 0.000000e+00 
   p2: 1.336620e-03 
   p3: -4.760020e-07 
   p4: 1.744120e-09 
inv_poly_parameters:
   p0: 441.554977 
   p1: 293.852005 
   p2: 37.695932 
   p3: 38.745264 
   p4: 21.601706 
   p5: 8.981299 
   p6: 4.295482 
   p7: 4.082164 
   p8: 3.517051 
   p9: 1.629742  
   p10: 0.304952
   p11: 0.0
   p12: 0.0
   p13: 0.0
   p14: 0.0
   p15: 0.0
   p16: 0.0
   p17: 0.0
   p18: 0.0 
   p19: 0.0 
affine_parameters:
   ac: 0.999977 
   ad: -0.000018 
   ae: 0.000018
   cx: 662.123354
   cy: 467.262942 


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9933825736079961, -0.006214058066792618, -0.1146841224158635,
         0.009561962263699604, 0.9995433275449167, 0.02866540141185659,
         0.1144536208672395, -0.02957231547880238, 0.9929883417380088]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.01746193243999558,0.04570631188028584,0.039410522812453984]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#added by wz 
center_x: 662.181371
center_y: 467.275447 
max_r: 470
min_r: 220



#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

acc_n: 0.02          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.02         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.002      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude



#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/shaozu/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -0.008                           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
```


Moreover, on uneven ground in outdoor experiments, the IMU has a great impact on vibration. If you want to improve performance, it is recommended to increase the visual weight.
```
 ProjectionFactor::sqrt_info = 10 * FOCAL_LENGTH / 1.5 * Matrix2d::Identity();
 ProjectionTdFactor::sqrt_info = 10 * FOCAL_LENGTH / 1.5 * Matrix2d::Identity();
```
